### PR TITLE
#164798300 List all users and their profiles

### PR DESCRIPTION
**Pull request by e-ian**
#### What does this PR do?
- This PR enables a registered user to view a list of all users and their profiles
#### Description of task to be completed?
- Listing of all users and their profiles
#### How should this be manually tested?
- Fetch and checkout into the branch ft-list-all-users164798300
- Create and activate your virtual environment
- pip install -r requirements.txt
- Make migrations with command `python manage.py makemmigrations`
- Run the command `python manage.py migrate` to migrate
- Source your .env file
- Run command python manage.py runserver
- Sign up, verify your email and login
- Then navigate to the endpoint `http://127.0.0.1:8000/api/v1/userslist/` using postman
#### What are the relevant pivotal tracker stories?
[164798300](https://www.pivotaltracker.com/story/show/164798300)

#### Screenshots
- Listing all users after logging in and access the endpoint for listing users
image

[Finishes #164798300]

### CODE REVIEW

**Review by patrickf949 — APPROVED** [review]
LGTM

**Review by Genza999 — APPROVED** [review]
LGTM

**Review by anyatibrian — APPROVED** [review]
I really liked, implementation of the logic great work

**Review by inno-asiimwe — APPROVED** [review]
LGTM

**Pull request merged**
