### PR TITLE
 #164798293 Enable article creation and manipulation

### PR DESCRIPTION
**Pull request by patrickf949**
#### What does this PR do?
Ensures a user can create and manipulate articles in Authors Haven

#### Description of Task to be completed?
- Start application for articles
- Write tests for article creation
- Implement article creation
- Implement article view, that is, all articles or one article 
- Add article edit functionality specific to article author
- Implement article deletion specific to the article author

#### How should this be manually tested?

Install the following
- python 3.5 or later
- postgreSQL 9 or later
- postman

After cloning the repo, change to its directory

Add correct credentials for environment variables as in the .env_sample file and source it
- `$ source .env_sample`

Run the following commands to activate the virtual environment
- `$ virtualenv venv`
- `$ source venv/bin/activate`

Install all requirements
- `$ pip install -r requirements.txt`

Make migrations
- `$ python manage.py makemigrations`
- `$ python manage.py migrate`

Run the server 
- `$ python manage.py runserver`

Test these endpoints in postman
[Run in Postman](https://app.getpostman.com/run-collection/5e383db2a97b3c80bd11)

#### What are the relevant pivotal tracker stories?
[#164798293](https://www.pivotaltracker.com/story/show/1#164798293)

#### Screen shots

- Create article

Screenshot 2019-04-10 at 23 17 58

- Update article

Screenshot 2019-04-10 at 23 21 43

- View all articles

Screenshot 2019-04-10 at 23 23 32

- View one article

Screenshot 2019-04-10 at 23 24 37

- Delete article

Screenshot 2019-04-10 at 23 26 18

### CODE REVIEW

**Review by anyatibrian — APPROVED** [review]
it awsome work, you have my approval

**Review by Genza999 — APPROVED** [review]
Great work Fitz!

**Review by e-ian — APPROVED** [review]
Good work @patrickf949 . Tested and LGTM

**Review by inno-asiimwe — APPROVED** [review]
LGTM

**Pull request merged**
