### PR TITLE
#164798305 Article custom search and filtering

### PR DESCRIPTION
**Pull request by e-ian**
#### What does this PR do?
- Adds a search functionality and custom filtering of articles based on parameters
#### Description of tasks to be completed 
- Add a custom filter class specifying filter parameters
- Add default filter backends in settings
- Add filter permission classes in views
- Add a method to check for permissions
#### How should this be manually tested?
- Fetch this branch by running the command git fetch origin `ft-custom-filter164798305` in the terminal.
- Check into the branch git checkout `ft-custom-filter164798305`
- Create and activate the virtual environment
- Install dependencies `pip install -r requirements.txt`
- Make migrations by running `python manage.py makemigrations`
- Run the command `python manage.py migrate` to run the migrations
- Run the application `python manage.py runserver`
- To filter by title, use `api/v1/articles/?title=title`
- To filter by author, use `api/v1/articles/?author=username_of_author`
- To filter by tags, use `api/v1/articles/?tagsList=tag`
- To search by keyword within the article use `api/v1/articles/?search=keyword`
#### What are the relevant pivotal tracker stories?
[#164798305](https://www.pivotaltracker.com/story/show/164798305)
#### Screenshots
- Filter by title
image
- Filter by tag
image
- Filter by author
image
- Filter by keyword
image

[Finishes #164798305]

### CODE REVIEW

**Review by anyatibrian — APPROVED** [review]
I really liked the way you have implemented the filter function,greate

**Review by Genza999 — APPROVED** [review]
LGTM

**Review by patrickf949 — APPROVED** [review]
LGTM

**Review by inno-asiimwe — APPROVED** [review]
LGTM

**Pull request merged**
