### PR TITLE
#164798285 Integrate coveralls

### PR DESCRIPTION
**Pull request by e-ian**
#### What does this PR do?
- Integrate coveralls code coverage service

#### Description of tasks to be completed
- Add coveralls.yml file
- Add coveralls script to travis.yml
- Add coveralls badge to README

#### How should this be manually tested?
[coveralls](https://coveralls.io/github/andela/ah-backend-prime?branch=develop)

#### Any background context you want to provide?
Coveralls ensures we are properly informed just how well our code base is tested which in turn provides quality assurance for the product

#### What are the relevant pivotal tracker stories?
[#164798285](https://www.pivotaltracker.com/story/show/164798285)

### CODE REVIEW

**Review by patrickf949 — APPROVED** [review]

**Review by anyatibrian — APPROVED** [review]
great work liked the fact that you change the branch develop

**Review by Genza999 — APPROVED** [review]
Good work mate!

**Comment by inno-asiimwe** [comment]
@e-ian please branch off from develop and perform this fix, also create a chore for it on the PT board, the PR description and commit message do not represent the actual work done.

**Comment by inno-asiimwe** [comment]
Closing this.

**Pull request closed without merging**
