### PR TITLE
#165852492 Fix social authentication

### PR DESCRIPTION
**Pull request by Genza999**
**What does this PR do?**
   Changes response format and fixes bugs in social-authentication response

**How should this be manually tested?**

- After cloning the repo, cd into it and run the following commands to activate the virtual environment
   `virtualenv venv`
   `source venv/bin/activate`

- **Checkout the branch with the validation implementation**
   `git checkout fix-social-auth-165852492`

- Install all requirements
   `pip install -r requirements.txt`

- Source the environment variables
  ` source .env`

- Run the migrations
   `python manage.py makemigrations`
   `python manage.py migrate`

- Run the server
   `python manage.py runserver`

**Testing Google Social Authentication**

  

- Navigate here to create an app

- Navigate here to obtain an access token for your account

- Navigate to Postman and use the URL http://127.0.0.1:8000/api/v1/social/auth/google/ and in the body section, paste the access token, change to a POST request and click SEND to view the response as shown in the screenshot below.

**Screenshot**
Screen Shot 2019-05-07 at 16 34 38

**What are the relevant pivotal tracker stories?**
   [#165852492](https://www.pivotaltracker.com/story/show/165852492)

### CODE REVIEW

**Review by e-ian — APPROVED** [review]
LGTM

**Review by patrickf949 — COMMENTED** [review]
Tested. LGTM

**Review by patrickf949 — APPROVED** [review]

**Review by anyatibrian — APPROVED** [review]
LGTM

**Review by patrickf949 — APPROVED** [review]

**Review by MuhanguziDavid — APPROVED** [review]
LGTM

**Pull request merged**
