### PR TITLE
#166026743 Create routes to fetch profiles of users followed/following a user

### PR DESCRIPTION
**Pull request by Genza999**
**What does this PR do?**
    This PR implements the functionality for users to be able to fetch/view the users following or users 
    followed by a particular user

**Description of Task to be completed?**
  

- Add routes to fetch the users following and followed by a user in the urls.py file

- Create class-based views for handling functionality for fetching users following or followed by a user

**How should this be manually tested?**

- After cloning the repo, cd into it and run the following commands to activate the virtual environment
   `virtualenv venv`
   `source venv/bin/activate`

- Checkout the branch with the functionality of users folllowing/unfollowing eachother
   `git checkout ft-users-follow-each-other-164798297`

- Install all requirements
   `pip install -r requirements.txt`

- Source the environment variables
   `source .env`

- Run the migrations
   `python manage.py makemigrations`
   `python manage.py migrate`

- Run the server
   `python manage.py runserver`

- To test out this functionality one has to first register on the application, in case of a successful registration, they will receive an account activation link on their email, this activation link would then be pasted in the URL section of postman and sent in order to activate and log into ones account where they would get a token which they would use in the Authorization section to access all other routes including the follows route.

- To view the users a particular user is following, you use the following endpoint:
    `http://127.0.0.1:8000/api/v1/profiles/following/{username}`

    
Screen Shot 2019-05-15 at 12 02 11

- To view the users following a particular user, you use the following endpoint:
    `http://127.0.0.1:8000/api/v1/profiles/followers/{username}`

Screen Shot 2019-05-15 at 12 04 45

**Relevant Pivotal Tracker Stories**
 
   [#166026743](https://www.pivotaltracker.com/story/show/166000024)

### CODE REVIEW

**Review by e-ian — APPROVED** [review]
LGTM

**Review by patrickf949 — COMMENTED** [review]
Great work @Genza999 
please maintain the test coverage though

**Review by anyatibrian — APPROVED** [review]
great work @Genza999, thanks for the team spirit

**Comment by Genza999** [comment]
> Great work @Genza999
> please maintain the test coverage though

Thanks. I have fixed it

**Pull request merged**
