### PR TITLE
#164798310 Users should be able to report an article

### PR DESCRIPTION
**Pull request by e-ian**
#### What does this PR do?
- Allows users to report articles that violate terms of authors'  heaven
#### Description of tasks to be completed
- Add a model to store reported articles
- Inform a user that their article has been reported and action is being taken
- Implement logic to prevent an author from reporting their own articles.
#### How should this be manually tested?
- Fetch this branch by running this command `git fetch origin ft-report-article-164798310` in the terminal
- Check into this branch by running `git checkout ft-report-article-164798310`
- Install dependencies by running `pip install -r requirements.txt`
- Run migrations by running `python manage.py migrate`
- Start the development server by running `python manage.py runserver`
- Make a `POST` request to `/api/v1/articles/<slug>/report/`
#### Sample request body
```
{ "violation": "This article is offensive" }
```
#### What are the relevant pivotal tracker stories?
[#164798310](https://www.pivotaltracker.com/story/show/164798310)

#### Screenshots
- Authenticated user reporting his own article
image
- Authenticated user reporting succeeds
image

- Email sent to author of reported article by admin
image

[Finishes #164798310]

### CODE REVIEW

**Review by Genza999 — APPROVED** [review]
LGTM. Great work Emma!

**Review by patrickf949 — APPROVED** [review]
Tested @e-ian LGTM

**Review by anyatibrian — APPROVED** [review]
great work, I really liked the implementation and flow

**Review by inno-asiimwe — APPROVED** [review]
LGTM

**Pull request merged**
